name: Test API Endpoints

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests

    - name: Run Flask app
      run: |
        nohup python app.py &
        sleep 10  # Wait for the server to start

    - name: Run API tests
      run: |
        python test_apis.py
